### ISSUE TITLE
Remove out of date documenation

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-frontend#119]
Initial documentation does not reflect update decisions for 2018 public data.

Review the docs in [this folder](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/) and remove the ones no longer needed/accurate.

**Comment by MattPerrine** [comment]
Reviewed the docs in [this folder](https://github.com/cfpb/hmda-platform/tree/master/docs/v2/spec) with David and agreed on the following disposition:

**Files for Devs - Leave as is**
[2018 Edit Descriptions.txt](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018%20Edit%20Descriptions.txt)
[2018_File_Spec_LAR.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_File_Spec_LAR.csv)	
[2018_File_Spec_TS.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_File_Spec_TS.csv)	
[2018_Institution_Data_Model_Spec.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Institution_Data_Model_Spec.csv)	

**Move to Web Documentation**

- [ ] [2018_Modified_LAR_Header.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Modified_LAR_Header.csv)
- [ ] [Modified LAR Schema.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/Modified%20LAR%20Schema.csv)
- [ ] [2018_Public_LAR_Code_Sheet_PDF.pdf](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_LAR_Code_Sheet_PDF.pdf)	

**Remove because they've already been replaced by Web Documentation** 

- [ ] [2018_Modified_LAR_Code_Sheet.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Modified_LAR_Code_Sheet.csv)	
- [ ] [2018_Modified_LAR_Data_Dictionary.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Modified_LAR_Data_Dictionary.csv)	
- [ ] [2018_Public_LAR_Data_Dictionary.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_LAR_Data_Dictionary.csv)
- [ ] [2018_Public_LAR_Data_Dictionary.pdf](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_LAR_Data_Dictionary.pdf)	
- [ ] [2018_Public_LAR_Header.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_LAR_Header.csv)	
- [ ] [2018_Public_Reporter_Panel_Data_Dictionary.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_Reporter_Panel_Data_Dictionary.csv)	
- [ ] [2018_Public_Reporter_Panel_Data_Dictionary.pdf](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_Reporter_Panel_Data_Dictionary.pdf)	
- [ ] [2018_Public_Reporter_Panel_Header.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_Reporter_Panel_Header.csv)	
- [ ] [2018_Public_TS_Data_Dictionary.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_TS_Data_Dictionary.csv)	
- [ ] [2018_Public_TS_Data_Dictionary.pdf](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_TS_Data_Dictionary.pdf)	
- [ ] [2018_Public_TS_Header.csv](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_TS_Header.csv)

**Comment by MattPerrine** [comment]
Will close this ticket once #207 is completed
