### ISSUE TITLE
Beta Platform reloads on 2022-Q1

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#1279]
If a user who does not have any 2022 institutions associated with their profile accesses the Beta platform through the link https://ffiec.beta.cfpb.gov/filing/2022-Q1/institutions, the page glitches/ reloads several times without any progress: 

![image](https://user-images.githubusercontent.com/58990254/147700158-c05f1a96-ef71-4a4c-8ca2-468798dcb338.png)

It seems that clicking the link in the Beta comms email redirects all users to a page with the 2022-Q1 link. 
@meissadia

**Comment by PatrickGoRaft** [comment]
This appears to be happening in production as well @meissadia  @audayshankar

**Comment by meissadia** [comment]
The issue is with our logic for redirecting users, without Quarterly institutions, who are accessing a Quarterly filing period: https://github.com/cfpb/hmda-frontend/blob/master/src/filing/institutions/index.jsx#L193-L195
 
We currently attempt to send users to the Annual filing period extracted from the Quarterly period.  Ex.  For `2022-Q1` we send non-quarterly users to `/filing/2022`. This logic is faulty since Annual/Quarterly filing for a given year are never simultaneously open. When we then access `/filing/2022`, our app recognizes that `2022 Annual` is not open and attempts to redirect users to the most recently opened filing period, which would again be `2022-Q1`, where the cycle starts again and we wind up in an infinite loop.

I think the fix here is to redirect users to the next available Annual filing period. 

Alternatively, we could sequentially redirect users through the previously opened filing periods, until we find one in which the user has actionable Institutions.
