### ISSUE TITLE
Update Frontend to use File Proxy Service

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-frontend#1547]
## Modified LAR:

Current link: `https://s3.amazonaws.com/cfpb-hmda-public/prod/modified-lar/<year>/<lei>.txt`
New link: `https://<dev>.cfpb.gov/file/modifiedLar/year/<year>/institution/<lei>/txt`

## IRS:

Current link: `https://s3.amazonaws.com/cfpb-hmda-public/prod/reports/disclosure/<period>/<lei>/nationwide/IRS.csv`
New Link: `https://<dev>.cfpb.gov/file/reports/irs/year/<period>/institution/<lei>`

New link now requires token

**Comment by meissadia** [comment]
Need Modified LAR to support files w/ header. [Request](https://github.com/cfpb/hmda-platform/pull/4497#issuecomment-1247055803)

**Comment by meissadia** [comment]
|Description|Screenshot|
|---|---|
|Currently we display the same message regardless of whether the IRS is available|![current](https://user-images.githubusercontent.com/2592907/192437939-f36c1bae-d726-4542-af65-d4d79e3190c3.png)|
|If an IRS is unavailable and a user clicks the link, they get a `Not found` page|![current-pending](https://user-images.githubusercontent.com/2592907/192438022-fb3e171a-8e9d-4845-9081-fbc7ffb3546c.png)|
|I would like to be able to make a `HEAD` call to check for a files existence and let the user know the file is not yet ready, if that's the case|![future-pending](https://user-images.githubusercontent.com/2592907/192438096-78aab740-4d68-4a41-882e-c548253b62da.png)|
|Otherwise, if the file exists, I'll show a download link|![future-ready](https://user-images.githubusercontent.com/2592907/192438163-47997287-368c-4862-b02c-6412adb05e26.png)|
