### ISSUE TITLE
[Markdown] Standardize Documentation

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1565]
Markdown document which discusses the updates to the new standardized markdown process.

**Comment by Michaeldremy** [comment]
# New Standardized Documentation Process 

The HMDA team has updated how markdown files are wrote within the documentation space. The motivation for these changes is to include a table of contents sidebar when viewing any documentation. This will allow for better navigation through these pages.

**_Table of contents sidebar:_**

<img width="262" alt="image" src="https://user-images.githubusercontent.com/60801873/193119794-581c928c-3898-4027-8d37-9587489eadfc.png">

## New Process

Before reading further please reference this [markdown file](https://github.com/cfpb/hmda-frontend/blob/master/src/documentation/markdown/2023/filing-faq.md). This file demonstrates proper use of the new process.

### Title

Title of the document now only contains one `#`.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/60801873/193120273-f8b07ed6-be34-4dd2-9804-77599cdcf794.png">


### Header

Headers will now contain two `#`. Be mindful when labeling these sections as they will be displayed in the table of contents sidebar. 

**Note:** please do not include special characters including `",\&*/'`

**_Table of content header_**

<img width="239" alt="image" src="https://user-images.githubusercontent.com/60801873/193120600-a45169a8-614c-421f-9030-ef48f3041db4.png">

**_Size of header on document_**

<img width="241" alt="image" src="https://user-images.githubusercontent.com/60801873/193123499-0dd1484d-025e-4a2e-aa91-58727c811c6a.png">


### Sub-header

Sub-headers will now contain three `#`.

**Note:** please do not include special characters including `",\&*/'`

**_Table of content sub-headers_**

<img width="219" alt="image" src="https://user-images.githubusercontent.com/60801873/193122574-a701300e-4314-41b5-b5d6-07464bc51768.png">

**_Sub-header on document_**

<img width="225" alt="image" src="https://user-images.githubusercontent.com/60801873/193120797-9c4c7cb5-1ee5-42fa-a3cd-6a5c4f7a7d47.png">


Following this process will help users better navigate our documentation pages!

**Comment by meissadia** [comment]
@Michaeldremy 

Maybe this becomes a page in the [Fontend Wiki](https://github.com/cfpb/hmda-frontend/wiki)?
 
Could also just live in the `/documentation/markdown/` folder and be linked from the [Frontend README](https://github.com/cfpb/hmda-frontend#hmda-frontend-projects)

**Comment by Michaeldremy** [comment]
Frontend wiki makes the most sense. I will move it there and then close out the ticket.

**Comment by meissadia** [comment]
@Michaeldremy 
> Frontend wiki makes the most sense. What section would you want the direct linking to be in the frontend readme?

![Screen Shot 2022-11-02 at 3 03 15 PM](https://user-images.githubusercontent.com/2592907/199602664-818fea9b-e154-47a4-8a43-494f6a70e95c.png)
 
I think at the end of the `Development` section we can add a `Creating and editing Markdown` with a blurb that `In order to correctly display a Table of Contents, headings in Markdown files need to conform to certain standards.   Please see the <link to wiki> for details.`

**Comment by Michaeldremy** [comment]
@meissadia 

Does this look good?

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/60801873/200045942-97c6412e-66f0-466b-9145-70e08c42b302.png">

**Comment by meissadia** [comment]
@Michaeldremy Requested changes to the above comment on the PR. 
 
Thoughts on this consolidated version of the Wiki page? I think we can probably even drop the `On documentation page` column because I don't think the displayed font size should be a consideration for Markdown creators, they should simply focus on the hierarchical structure. 

## Motivation
||Table of Contents|
|---|---|
|To help users navigate our Documentation pages, we now display a Table of Contents (TOC). In order for the TOC to be correctly populated, Markdown files must conform to certain standards.<br/><br/>This guide uses the [Filing FAQ file](https://github.com/cfpb/hmda-frontend/blob/master/src/documentation/markdown/2023/filing-faq.md) as a reference.<br/>|<img width="350" alt="toc" src="https://user-images.githubusercontent.com/2592907/200083119-c97270fd-895d-4c8d-baa6-62a83a1be812.png">|

## Headings
The TOC is dynamically populated by the headings in our Markdown files. Only Section headings and sub-headings are included. 

**Note:** please do not include special characters including `",\&*/'`

|Element| Markdown Example | In TOC | On documentation page|
|---|---|---|---|
|Document Title|\# HMDA Filing - Frequently Asked Questions|Not Shown|<img width="300" alt="image" src="https://user-images.githubusercontent.com/60801873/193120273-f8b07ed6-be34-4dd2-9804-77599cdcf794.png">|
|Section Heading|\#\# Account Registration|<img width="300" alt="image" src="https://user-images.githubusercontent.com/60801873/193120600-a45169a8-614c-421f-9030-ef48f3041db4.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/60801873/193123499-0dd1484d-025e-4a2e-aa91-58727c811c6a.png">|
|Section Sub-heading|\#\#\# What is my agency code?|<img width="300" alt="image" src="https://user-images.githubusercontent.com/60801873/193122574-a701300e-4314-41b5-b5d6-07464bc51768.png">|<img width="225" alt="image" src="https://user-images.githubusercontent.com/60801873/193120797-9c4c7cb5-1ee5-42fa-a3cd-6a5c4f7a7d47.png">|

**Comment by Michaeldremy** [comment]
@meissadia This looks good! 

I agree I don't think we need to add the `On documentation page` section of the table. Originally I added it to give more context of what the person was creating from the markdown but like you said it's not super relevant information.
