### ISSUE TITLE
Upgrade Cypress

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#1655]
Cypress 
- v10
- v11?

**Comment by Michaeldremy** [comment]
`cypress` has been upgraded to v11.

No major changes to the code.

v11 update introduces two new things to the ecosystem.

### Component Testing Released
--------------------------

Component Testing is now generally available for projects using React, Next.js, Angular, and Vue!

Component tests allow you to see and test your application’s components in a real browser as you work. You can use your favorite Cypress commands and features to develop your components without running your whole app. [Learn more in our blog post.](https://on.cypress.io/cypress-11-release)

Existing Component Testing users, see the [changelog](https://on.cypress.io/changelog#11-0-0) to learn about breaking changes.

### Faster Startup Time
-------------------

We have also massively improved our startup performance by shipping a snapshot of our binary instead of the source files. Results will vary based on your situation, but we saw up to 84% faster startup times!
