### ISSUE TITLE
Explore website wide search

### ISSUE THREAD

**Issue by Michaeldremy** [cfpb/hmda-frontend#1657]
Concept:

Allow users the ability to search for any documentation while simultaneously being anywhere in the platform.

Possible library to use:

- https://lunrjs.com/

**Comment by meissadia** [comment]
In terms of generating our own search index: 

[Docusaurus has plugins for Lunr]( https://docusaurus.io/community/resources#community-plugins) 
 
Seems like that would only apply to Documentation since the plugins operate by parsing and indexing content from the Markdown files while much of our website is in JSX and dynamically rendered via React.

**Comment by meissadia** [comment]
- Generate a Lunr index
  - https://lunrjs.com/guides/getting_started.html#creating-an-index
  - Leverage a DS plugin to generate the portion based on Markdown content?
    - https://docusaurus.io/community/resources#search
  - Create a way to index the rest of our site
- Serialize the index so we don't have to rebuild it constantly
  - https://lunrjs.com/guides/index_prebuilding.html
- Integrate the index into the Docusuaurus search bar
- Integrate the DS search bar into the rest of the site's navbar

**Comment by Michaeldremy** [comment]
Closing ticket as we are using Algolia in the FE to search our documentation.
