### ISSUE TITLE
400 Error for Formatting Errors

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#1722]
The platform is throwing an Error 400 on files that have ~formatting error of Incorrect Number of LAR fields~ certain formatting errors. Can we review how the UI handles formatting error responses so we can provide a clearer error description to the user? 

![image](https://user-images.githubusercontent.com/58990254/217588788-c4f1663a-95e3-457d-81d1-254836ae306c.png)

I can provide a test file that is resulting in these errors, if needed.

**Comment by meissadia** [comment]
Hey Abhi, 

Please provide a test file for the issue you're seeing.  In PROD, when I upload a file with an incorrect number of LAR fields I'm see the correct UI outlining the error.

<img width="1365" alt="prod-incorrect-number-fields-lar" src="https://user-images.githubusercontent.com/2592907/217612699-7ce118cc-6b9f-4a2d-b62d-45c30a01c113.png">

---

When both TS & LAR have incorrect number of fields, still seeing the correct UI providing those details.
<img width="1003" alt="prod-incorrect-number-fields-both" src="https://user-images.githubusercontent.com/2592907/217613425-dbe87574-bb7a-40d0-9d19-35b296255c11.png">

**Comment by meissadia** [comment]
## Update
I've updated the code to pull the more detailed error message from the API response's JSON payload.  So here we see the message `Invalid file format` instead of `Bad Request` or no explanatory text at all. 

<img width="959" alt="upload-more-detail" src="https://user-images.githubusercontent.com/2592907/217671154-9222518b-0e6c-428c-818d-e4bca55f041e.png">

## Thought
Might we want to link users to the FFVT in this scenario?  Actually, after further testing, the FFVT does not seem to catch the issue of a trailing blank line. So that might just further confuse a user. We may want to request the expansion of the FFVT to catch this issue. 
 
As an alternate fix: Uploading a LAR file that has this formatting issue to the [OLARFT](https://ffiec.beta.cfpb.gov/tools/lar-formatting) and then downloading the file will eliminate the error.

**Comment by meissadia** [comment]
Updated code deployed to the DEV environment for verification.

**Comment by meissadia** [comment]
After further testing, the trailing newline is not the source of the upload failure.  Instead, it seems that the presence of an excessive number of trailing spaces causes the Platform API to fail while processing the LAR file.  
 
As I continue to explore I'm finding that the upload failure it's not particular to spaces but rather to the line length.  A line containing 2,049+ characters triggers the `Invalid file format` error regardless (from my limited testing) of what the last character on the line is. 

Below is a LAR file with 1 TS row and 1 LAR row.  The LAR row's character count is 2,049 and triggers the error mentioned above. If you delete the last `1` in the file and re-upload, you should instead see the more detailed UI outlining the formatting errors found.
 
[2022-FRONTENDTESTBANK9999.txt](https://github.com/cfpb/hmda-frontend/files/10700036/2022-FRONTENDTESTBANK9999.txt)
