### ISSUE TITLE
Failing Graphs Test

### ISSUE THREAD

**Issue by ojbravo** [cfpb/hmda-frontend#1855]
Updated Graphs test to accommodate available data so that tests don't fail in Prod.

**Comment by Michaeldremy** [comment]
The reason for the test failing is because the Graphs endpoint returns an empty string for the `overview` key/value pair.

<img width="246" alt="image" src="https://github.com/cfpb/hmda-frontend/assets/60801873/7485e00e-7dd5-43af-bf63-fc4e4f9ad5b8">

The `overview` key/value pair is typically displayed here... Right now we are using a backup sentence for when the `overview` key/value pair from the endpoint is failing. Typically this sentence will display something along the lines of "X institutions data is collected and the data represents this".

<img width="763" alt="image" src="https://github.com/cfpb/hmda-frontend/assets/60801873/9deb6769-a34e-4aaf-8628-bd68e95afb3b">

**Comment by ojbravo** [comment]
The Graphs header is working in dev. Just needs to be deployed to Prod...
<img width="769" alt="Screenshot 2024-04-08 at 12 02 29 PM" src="https://github.com/cfpb/hmda-frontend/assets/3650300/707fbe69-945c-4630-b0ab-30de90719975">
