### ISSUE TITLE
Data Browser Maps & Graphs shows blank screen on Google Chrome

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#251]
Short description explaining the high-level reason for the new issue.

## Current behavior
When using Chrome, upon selecting the maps & graphs link in the dev environment, the screen goes blank. 

## Steps to replicate behavior (include URLs)

1. Head to dev site

## Screenshots
![image](https://user-images.githubusercontent.com/41752348/74861755-df5dac00-5318-11ea-9eb4-84add4bea564.png)

**Comment by meissadia** [comment]
I'm not able to reproduce this in `dev` or `dev-beta`.   

One potential work around that did not pan out:
```
- Open chrome://flags/
- Set the "Override software rendering list" to 'Enabled'
- Reload the map and see if you still get the same error.
```

@chynnakeys Can you try visiting the mapbox examples page to see if you get a similar error?  That might help determine if the error is due to the machine or if it's somewhere in the Maps implementation.  https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

Can you also visit the url [chrome://gpu/](chrome://gpu/) and check the status of WebGL?
<img width="456" alt="Screen Shot 2020-02-19 at 4 50 04 PM" src="https://user-images.githubusercontent.com/2592907/74887372-f6f85d00-5337-11ea-9822-2bd03970c47f.png">

**Comment by chynnakeys** [comment]
@meissadia the mapbox doc shows this message 
![image](https://user-images.githubusercontent.com/41752348/74947918-90bc1a80-53c9-11ea-995e-999727eee2c0.png)

The chrome gpu shows this:
![image](https://user-images.githubusercontent.com/41752348/74947962-9fa2cd00-53c9-11ea-895a-aca0b42c1688.png)

are these conflicting?

**Comment by wpears** [comment]
Have you recently applied an update to your browser @chynnakeys? Have you restarted it since then?

Could be WebGL is being limited by a bureau policy which would be quite unfortunate, but unsure yet if that's the cause.

**Comment by chynnakeys** [comment]
I haven't applied an update @wpears, but i did restart my computer.
