### ISSUE TITLE
Data Browser FAQ page connection failure from dev homepage

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-frontend#277]
Selecting the FAQ page from the dev environment creates a connection failure. You can only visit the FAQ page from the documentation page. 

![image](https://user-images.githubusercontent.com/41752348/75822589-38443000-5d6e-11ea-9f04-1471ea58e955.png)

"upstream connect error or disconnect/reset before headers. reset reason: connection failure"

**Comment by wpears** [comment]
This is actually happening for all of /documentation when visited directly (ie `<dev-domain>/documentation/`). Something is likely misconfigured in kubernetes outside of this repo. That said, I will still convert the FAQ link to use the browser-side router rather than hard-linking via an anchor tag.
