### ISSUE TITLE
Clarify language under Help for Filers for 2017/2018

### ISSUE THREAD

**Issue by meissadia** [cfpb/hmda-frontend#703]
## Differences:
- 2019+ link directly to the FIG for that year
- 2017/2018 links to a Documentation page

## Options:
- Unify links by pointing 2017/2018 directly at the FIGs
- Change language describing the 2017/2018 link

## Screenshot:
![Screen Shot 2020-09-24 at 11 52 06 AM](https://user-images.githubusercontent.com/2592907/94181334-92b4f300-fe5c-11ea-96da-f66e599dbfcb.png)

**Comment by audayshankar** [comment]
I like the first option of unifying the links like below, since it's the most uniform. 
- [For Data Collected in 2018](https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2018-hmda-fig.pdf)
- [For Data Collected in 2017](https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2017-hmda-fig.pdf)

I assume it was initially written as-is to be more concise since less people are looking for 2017 and 2018 FIGs right now, but changing it to be uniform takes up approximately the same amount of space.
