### ISSUE TITLE
File upload page throws an error when file upload is cancelled in the middle

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-frontend#90]
Short description explaining the high-level reason for the new issue.

## Current behavior

<img width="1663" alt="Screen Shot 2019-12-23 at 9 43 34 AM" src="https://user-images.githubusercontent.com/44377678/71364096-2291dd80-2569-11ea-8a44-293fbedb64c8.png">

## Steps to replicate behavior (include URLs)

1.

**Comment by meissadia** [comment]
I've done a handful of uploads for Bank 0 in `prod-beta` but have not been able to replicate this issue.

**Comment by omnipresent07** [comment]
Steps to recreate

Do a good filing (with sign)
Click Filing home
Go Back
Go Fwd
Submission page (do not upload new file)
Back — Notice that you are back at the sign page with Error message on top.

**Comment by wpears** [comment]
What browser was this done in?

**Comment by omnipresent07** [comment]
Chrome.

**Comment by meissadia** [comment]
I've been able to replicate in Chrome and Safari. 

- Complete a filing
- Click `Filing Home`
- Start a new Submission (do not upload new file)
- Click Back

My observation: 

Instead of being taken back to the `/institutions` page, the user stays on the `/{{lei}}/submission` page and is routed to `Step 5: Submission`. The front-end tries to make an API call to retrieve the submission summary for newly started submission, which fails.
