### ISSUE TITLE
Add more detail to Filing Summary Page

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#917]
On the Filing Summary page, after a user completes their filing, we should add more detail regarding the Respondent Information.

Suggested wording: "The respondent information shown below is pulled directly from your file. If you see any updates that need to be made, you will need to update the Transmittal Sheet (first row) of your file"

![image](https://user-images.githubusercontent.com/58990254/115051042-602b2000-9eaa-11eb-841b-9006cf31c29b.png)

**Comment by meissadia** [comment]
@audayshankar Thoughts on proposed changes?
- Adds some separation between Respondent Info and File Info
- Adds section descriptions
- Respondent Info description indicates that users should update/resubmit LAR to apply RI changes.


| Current | Proposed | 
|--|--|
| <img width="100%" alt="Screen Shot 2021-04-19 at 1 14 26 PM" src="https://user-images.githubusercontent.com/2592907/115291008-75ee4e80-a111-11eb-8565-25187269f7d0.png"> | <img width="100%" alt="Screen Shot 2021-04-19 at 1 15 18 PM" src="https://user-images.githubusercontent.com/2592907/115291031-7b4b9900-a111-11eb-8784-68abca910604.png"> |

**Comment by audayshankar** [comment]
These changes look great!

**Comment by meissadia** [comment]
@chynnakeys @audayshankar 
 
**Changes**
- Add a link to [TS fields](http://ffiec.cfpb.gov/documentation/2021/ts-data-fields/) for context
- Since the same `To make changes` note applies to both Respondent Info and File Info, I've moved this message into a shared space.  Added some color and an icon to help connect the message to the sections it applies to.
- Additional section differentiation
- Made the RI/FI sections full-width, the previous indentation of the sections felt "off" to me.

**Questions**
- Does this make that top section too busy/cluttered?

<img width="842" alt="Screen Shot 2021-04-21 at 11 49 13 AM" src="https://user-images.githubusercontent.com/2592907/115598516-bf68a600-a297-11eb-8da5-483c967f35ee.png">
